# Generated by Django 3.2.12 on 2022-06-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descriptif', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dateper', models.DateField()),
                ('photo', models.ImageField(upload_to='photosprod')),
                ('marque', models.CharField(max_length=255)),
                ('prix', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('cat', models.ForeignKey(db_column='cat', on_delete=django.db.models.deletion.DO_NOTHING, to='drive.catprod')),
            ],
        ),
    ]
