# Generated by Django 3.2.12 on 2022-06-12 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='datecommande',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commandes', models.ManyToManyField(blank=True, to='drive.Commande')),
            ],
        ),
    ]
