# Generated by Django 3.2.12 on 2022-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_auto_20220612_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
