# Generated by Django 3.2.12 on 2022-06-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_alter_commande_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date',
        ),
    ]
