# Generated by Django 3.2.12 on 2022-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_remove_commande_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photosprod'),
        ),
    ]
